/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_modifier (void);
GtkWidget* create_Maintenance (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_window1 (void);
GtkWidget* create_windowajoute (void);
GtkWidget* create_window3 (void);
GtkWidget* create_windowcapteur (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window5 (void);
