/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed1;
  GtkWidget *entry12_id;
  GtkWidget *entry13_prix;
  GtkWidget *label1;
  GtkWidget *input;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button4;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *combobox2;
  GtkWidget *combobox3;
  GtkWidget *label13;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (modifier), fixed1);

  entry12_id = gtk_entry_new ();
  gtk_widget_show (entry12_id);
  gtk_fixed_put (GTK_FIXED (fixed1), entry12_id, 152, 304);
  gtk_widget_set_size_request (entry12_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12_id), 8226);

  entry13_prix = gtk_entry_new ();
  gtk_widget_show (entry13_prix);
  gtk_fixed_put (GTK_FIXED (fixed1), entry13_prix, 144, 136);
  gtk_widget_set_size_request (entry13_prix, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13_prix), 8226);

  label1 = gtk_label_new (_("ID a modifier"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 16, 56);
  gtk_widget_set_size_request (label1, 112, 32);

  input = gtk_entry_new ();
  gtk_widget_show (input);
  gtk_fixed_put (GTK_FIXED (fixed1), input, 136, 56);
  gtk_widget_set_size_request (input, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (input), 8226);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 456, 16);
  gtk_widget_set_size_request (button1, 104, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  button2 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 344, 152);
  gtk_widget_set_size_request (button2, 104, 32);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 336, 296);
  gtk_widget_set_size_request (button3, 120, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button3), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 456, 72);
  gtk_widget_set_size_request (button4, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button4), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("prix"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 0, 136);
  gtk_widget_set_size_request (label5, 136, 24);

  label6 = gtk_label_new (_("type de materiel"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 8, 200);
  gtk_widget_set_size_request (label6, 128, 25);

  label7 = gtk_label_new (_("marque"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 56, 256);
  gtk_widget_set_size_request (label7, 88, 25);
  GTK_WIDGET_SET_FLAGS (label7, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (label7), TRUE);

  label8 = gtk_label_new (_("id"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 40, 304);
  gtk_widget_set_size_request (label8, 112, 32);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox2, 160, 184);
  gtk_widget_set_size_request (combobox2, 144, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("charrue"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("d\303\251chameuse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("cultivateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("motoculture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("d\303\251compacteur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("butteuse"));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox3, 160, 248);
  gtk_widget_set_size_request (combobox3, 144, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("john_deere"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("aebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("landini"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("alpego"));

  label13 = gtk_label_new ("");
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 144, 336);
  gtk_widget_set_size_request (label13, 168, 32);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_retour_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button3_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button4_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_afficherM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (modifier, entry12_id, "entry12_id");
  GLADE_HOOKUP_OBJECT (modifier, entry13_prix, "entry13_prix");
  GLADE_HOOKUP_OBJECT (modifier, label1, "label1");
  GLADE_HOOKUP_OBJECT (modifier, input, "input");
  GLADE_HOOKUP_OBJECT (modifier, button1, "button1");
  GLADE_HOOKUP_OBJECT (modifier, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (modifier, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (modifier, image1, "image1");
  GLADE_HOOKUP_OBJECT (modifier, label2, "label2");
  GLADE_HOOKUP_OBJECT (modifier, button2, "button2");
  GLADE_HOOKUP_OBJECT (modifier, button3, "button3");
  GLADE_HOOKUP_OBJECT (modifier, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (modifier, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (modifier, image2, "image2");
  GLADE_HOOKUP_OBJECT (modifier, label3, "label3");
  GLADE_HOOKUP_OBJECT (modifier, button4, "button4");
  GLADE_HOOKUP_OBJECT (modifier, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (modifier, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (modifier, image3, "image3");
  GLADE_HOOKUP_OBJECT (modifier, label4, "label4");
  GLADE_HOOKUP_OBJECT (modifier, label5, "label5");
  GLADE_HOOKUP_OBJECT (modifier, label6, "label6");
  GLADE_HOOKUP_OBJECT (modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier, label8, "label8");
  GLADE_HOOKUP_OBJECT (modifier, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (modifier, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (modifier, label13, "label13");

  return modifier;
}

GtkWidget*
create_Maintenance (void)
{
  GtkWidget *Maintenance;
  GtkWidget *alignment4;
  GtkWidget *fixed2;
  GtkWidget *separatortoolitem1;
  GtkWidget *treeview1;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *button8;
  GtkWidget *label13;
  GtkWidget *label14;

  Maintenance = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Maintenance), _("Interface maintenance "));
  gtk_window_set_destroy_with_parent (GTK_WINDOW (Maintenance), TRUE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Maintenance), alignment4);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (alignment4), fixed2);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_fixed_put (GTK_FIXED (fixed2), separatortoolitem1, 304, 168);
  gtk_widget_set_size_request (separatortoolitem1, 16, 16);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 376, 176);
  gtk_widget_set_size_request (treeview1, 448, 240);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 24, 144);
  gtk_widget_set_size_request (button5, 232, 72);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter un materiel /afficher"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 24, 248);
  gtk_widget_set_size_request (button6, 232, 64);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 24, 352);
  gtk_widget_set_size_request (button7, 232, 72);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("eliminer le materieu"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  button8 = gtk_button_new_with_mnemonic (_("afficher capteur alarmante"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 40, 464);
  gtk_widget_set_size_request (button8, 176, 56);

  label13 = gtk_label_new_with_mnemonic (_("<b>param\303\251tres :</b>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 88, 80);
  gtk_widget_set_size_request (label13, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label13), TRUE);

  label14 = gtk_label_new (_("affichage des equipments :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 448, 120);
  gtk_widget_set_size_request (label14, 289, 41);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button4_eliminer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_affichercapteur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Maintenance, Maintenance, "Maintenance");
  GLADE_HOOKUP_OBJECT (Maintenance, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Maintenance, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Maintenance, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (Maintenance, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Maintenance, button5, "button5");
  GLADE_HOOKUP_OBJECT (Maintenance, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Maintenance, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Maintenance, image4, "image4");
  GLADE_HOOKUP_OBJECT (Maintenance, label10, "label10");
  GLADE_HOOKUP_OBJECT (Maintenance, button6, "button6");
  GLADE_HOOKUP_OBJECT (Maintenance, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Maintenance, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Maintenance, image5, "image5");
  GLADE_HOOKUP_OBJECT (Maintenance, label11, "label11");
  GLADE_HOOKUP_OBJECT (Maintenance, button7, "button7");
  GLADE_HOOKUP_OBJECT (Maintenance, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Maintenance, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Maintenance, image6, "image6");
  GLADE_HOOKUP_OBJECT (Maintenance, label12, "label12");
  GLADE_HOOKUP_OBJECT (Maintenance, button8, "button8");
  GLADE_HOOKUP_OBJECT (Maintenance, label13, "label13");
  GLADE_HOOKUP_OBJECT (Maintenance, label14, "label14");

  return Maintenance;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed3;
  GtkWidget *entry10_id;
  GtkWidget *entry9_prix;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *button9;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label18;
  GtkWidget *button10;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label19;
  GtkWidget *button11;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *comboboxentry1;
  GtkWidget *combobox1;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("ajouter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed3);

  entry10_id = gtk_entry_new ();
  gtk_widget_show (entry10_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry10_id, 264, 128);
  gtk_widget_set_size_request (entry10_id, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10_id), 8226);

  entry9_prix = gtk_entry_new ();
  gtk_widget_show (entry9_prix);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9_prix, 264, 184);
  gtk_widget_set_size_request (entry9_prix, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9_prix), 8226);

  label15 = gtk_label_new (_("ajouter materiel"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 216, 8);
  gtk_widget_set_size_request (label15, 192, 17);

  label16 = gtk_label_new (_("type de material"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 120, 32);
  gtk_widget_set_size_request (label16, 144, 32);

  label17 = gtk_label_new (_("marque"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 160, 80);
  gtk_widget_set_size_request (label17, 80, 24);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed3), button9, 128, 296);
  gtk_widget_set_size_request (button9, 96, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button9), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox7), label18, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 472, 96);
  gtk_widget_set_size_request (button10, 128, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button10), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox8), label19, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 448, 296);
  gtk_widget_set_size_request (button11, 90, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox9), label20, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("id"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 152, 128);
  gtk_widget_set_size_request (label21, 112, 24);

  label22 = gtk_label_new (_("prix"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 192, 192);
  gtk_widget_set_size_request (label22, 41, 17);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry1, 264, 32);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("charrue"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("d\303\251chameuse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("cultivateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("motoculture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("d\303\251compacteur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("butteuse"));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 264, 80);
  gtk_widget_set_size_request (combobox1, 184, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("john_deere"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("aebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("landini"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("alpego"));

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button3_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button4_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_retour_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter, entry10_id, "entry10_id");
  GLADE_HOOKUP_OBJECT (ajouter, entry9_prix, "entry9_prix");
  GLADE_HOOKUP_OBJECT (ajouter, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter, label16, "label16");
  GLADE_HOOKUP_OBJECT (ajouter, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajouter, button9, "button9");
  GLADE_HOOKUP_OBJECT (ajouter, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter, label18, "label18");
  GLADE_HOOKUP_OBJECT (ajouter, button10, "button10");
  GLADE_HOOKUP_OBJECT (ajouter, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajouter, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajouter, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter, label19, "label19");
  GLADE_HOOKUP_OBJECT (ajouter, button11, "button11");
  GLADE_HOOKUP_OBJECT (ajouter, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ajouter, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajouter, image9, "image9");
  GLADE_HOOKUP_OBJECT (ajouter, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajouter, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajouter, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajouter, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (ajouter, combobox1, "combobox1");

  return ajouter;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed4;
  GtkWidget *entry15_id;
  GtkWidget *label23;
  GtkWidget *button12;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label24;
  GtkWidget *button13;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *button14;
  GtkWidget *alignment13;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label26;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed4);

  entry15_id = gtk_entry_new ();
  gtk_widget_show (entry15_id);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15_id, 136, 112);
  gtk_widget_set_size_request (entry15_id, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15_id), 8226);

  label23 = gtk_label_new (_("id"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 72, 120);
  gtk_widget_set_size_request (label23, 41, 17);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed4), button12, 304, 112);
  gtk_widget_set_size_request (button12, 136, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button12), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed4), button13, 304, 176);
  gtk_widget_set_size_request (button13, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button13), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed4), button14, 168, 176);
  gtk_widget_set_size_request (button14, 96, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button14), alignment13);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox12), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button5_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_retour_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_afficherS_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer, entry15_id, "entry15_id");
  GLADE_HOOKUP_OBJECT (supprimer, label23, "label23");
  GLADE_HOOKUP_OBJECT (supprimer, button12, "button12");
  GLADE_HOOKUP_OBJECT (supprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (supprimer, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (supprimer, image10, "image10");
  GLADE_HOOKUP_OBJECT (supprimer, label24, "label24");
  GLADE_HOOKUP_OBJECT (supprimer, button13, "button13");
  GLADE_HOOKUP_OBJECT (supprimer, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (supprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (supprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer, label25, "label25");
  GLADE_HOOKUP_OBJECT (supprimer, button14, "button14");
  GLADE_HOOKUP_OBJECT (supprimer, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (supprimer, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (supprimer, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer, label26, "label26");

  return supprimer;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed5;
  GtkWidget *label27;
  GtkWidget *button15;
  GtkWidget *alignment14;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label28;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window1), fixed5);

  label27 = gtk_label_new (_("materieu supprimer"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 144, 88);
  gtk_widget_set_size_request (label27, 224, 97);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed5), button15, 344, 200);
  gtk_widget_set_size_request (button15, 136, 45);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button15), alignment14);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox13), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_retour_MT_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, button15, "button15");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");

  return window1;
}

GtkWidget*
create_windowajoute (void)
{
  GtkWidget *windowajoute;
  GtkWidget *fixed6;
  GtkWidget *label29;
  GtkWidget *button16;
  GtkWidget *alignment15;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label30;

  windowajoute = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowajoute), _("window2"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowajoute), fixed6);

  label29 = gtk_label_new (_("materieu ajout\303\251"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 136, 88);
  gtk_widget_set_size_request (label29, 240, 73);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed6), button16, 344, 192);
  gtk_widget_set_size_request (button16, 136, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button16), alignment15);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox14), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_retour_MA_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowajoute, windowajoute, "windowajoute");
  GLADE_HOOKUP_OBJECT (windowajoute, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowajoute, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowajoute, button16, "button16");
  GLADE_HOOKUP_OBJECT (windowajoute, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowajoute, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowajoute, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowajoute, label30, "label30");

  return windowajoute;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed7;
  GtkWidget *label31;
  GtkWidget *button17;
  GtkWidget *alignment16;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label32;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window3), fixed7);

  label31 = gtk_label_new (_("materieu modifier"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed7), label31, 128, 72);
  gtk_widget_set_size_request (label31, 280, 97);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed7), button17, 384, 200);
  gtk_widget_set_size_request (button17, 112, 45);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button17), alignment16);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox15), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_retour_MM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window3, label31, "label31");
  GLADE_HOOKUP_OBJECT (window3, button17, "button17");
  GLADE_HOOKUP_OBJECT (window3, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window3, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window3, image15, "image15");
  GLADE_HOOKUP_OBJECT (window3, label32, "label32");

  return window3;
}

GtkWidget*
create_windowcapteur (void)
{
  GtkWidget *windowcapteur;
  GtkWidget *fixed8;
  GtkWidget *treeview2;
  GtkWidget *button18;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label34;
  GtkWidget *label33;

  windowcapteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowcapteur), _("window4"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (windowcapteur), fixed8);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 264, 144);
  gtk_widget_set_size_request (treeview2, 416, 272);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed8), button18, 736, 48);
  gtk_widget_set_size_request (button18, 122, 45);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button18), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox16), label34, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("nombre de capteur alarmantes:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed8), label33, 344, 80);
  gtk_widget_set_size_request (label33, 272, 48);

  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_retour_capteur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowcapteur, windowcapteur, "windowcapteur");
  GLADE_HOOKUP_OBJECT (windowcapteur, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowcapteur, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowcapteur, button18, "button18");
  GLADE_HOOKUP_OBJECT (windowcapteur, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (windowcapteur, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (windowcapteur, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowcapteur, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowcapteur, label33, "label33");

  return windowcapteur;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed9;
  GtkWidget *fixed10;
  GtkWidget *entry7_c;
  GtkWidget *entry8_c;
  GtkWidget *entry9_c;
  GtkWidget *entry10_c;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *entry11_c;
  GtkWidget *entry12_c;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *combobox4;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *button19;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label53;
  GtkWidget *label37;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window4, 700, 500);
  gtk_window_set_title (GTK_WINDOW (window4), _("creation_compte"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window4), fixed9);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed9), fixed10, 0, 0);
  gtk_widget_set_size_request (fixed10, 0, 0);

  entry7_c = gtk_entry_new ();
  gtk_widget_show (entry7_c);
  gtk_fixed_put (GTK_FIXED (fixed10), entry7_c, 216, 96);
  gtk_widget_set_size_request (entry7_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7_c), 8226);

  entry8_c = gtk_entry_new ();
  gtk_widget_show (entry8_c);
  gtk_fixed_put (GTK_FIXED (fixed10), entry8_c, 216, 136);
  gtk_widget_set_size_request (entry8_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8_c), 8226);

  entry9_c = gtk_entry_new ();
  gtk_widget_show (entry9_c);
  gtk_fixed_put (GTK_FIXED (fixed10), entry9_c, 216, 176);
  gtk_widget_set_size_request (entry9_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9_c), 8226);

  entry10_c = gtk_entry_new ();
  gtk_widget_show (entry10_c);
  gtk_fixed_put (GTK_FIXED (fixed10), entry10_c, 216, 216);
  gtk_widget_set_size_request (entry10_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10_c), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton1, 216, 264);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton2, 304, 264);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 1919, 2001, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton3, 384, 264);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  entry11_c = gtk_entry_new ();
  gtk_widget_show (entry11_c);
  gtk_fixed_put (GTK_FIXED (fixed10), entry11_c, 216, 344);
  gtk_widget_set_size_request (entry11_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11_c), 8226);

  entry12_c = gtk_entry_new ();
  gtk_widget_show (entry12_c);
  gtk_fixed_put (GTK_FIXED (fixed10), entry12_c, 216, 304);
  gtk_widget_set_size_request (entry12_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12_c), 8226);

  label35 = gtk_label_new ("");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed10), label35, 448, 312);
  gtk_widget_set_size_request (label35, 112, 17);

  label36 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Cr\303\251er votre compte </b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed10), label36, 184, 8);
  gtk_widget_set_size_request (label36, 280, 72);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label38 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Mot de passe</b></span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed10), label38, 24, 128);
  gtk_widget_set_size_request (label38, 176, 56);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label39 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Nom:</b></span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed10), label39, 64, 184);
  gtk_widget_set_size_request (label39, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  label40 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Prenom: </b></span>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed10), label40, 48, 216);
  gtk_widget_set_size_request (label40, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label41 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Date de naissance</b></span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed10), label41, 32, 256);
  gtk_widget_set_size_request (label41, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label42 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>N\302\260Telephone: </b></span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed10), label42, 40, 312);
  gtk_widget_set_size_request (label42, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label43 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Pays</b></span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed10), label43, 64, 344);
  gtk_widget_set_size_request (label43, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label44 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Sexe:</b></span>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed10), label44, 64, 376);
  gtk_widget_set_size_request (label44, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed10), combobox4, 226, 373);
  gtk_widget_set_size_request (combobox4, 121, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Homme\t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Femme"));

  label45 = gtk_label_new (_("donn\303\251e invalide"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed10), label45, 440, 96);
  gtk_widget_set_size_request (label45, 112, 25);

  label46 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed10), label46, 448, 136);
  gtk_widget_set_size_request (label46, 120, 25);

  label47 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed10), label47, 440, 176);
  gtk_widget_set_size_request (label47, 120, 25);

  label48 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed10), label48, 440, 224);
  gtk_widget_set_size_request (label48, 112, 17);

  label49 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed10), label49, 464, 264);
  gtk_widget_set_size_request (label49, 120, 25);

  label50 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed10), label50, 448, 313);
  gtk_widget_set_size_request (label50, 136, 16);

  label51 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed10), label51, 448, 344);
  gtk_widget_set_size_request (label51, 128, 17);

  label52 = gtk_label_new (_("donne invalide"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed10), label52, 440, 384);
  gtk_widget_set_size_request (label52, 144, 17);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed10), button19, 200, 440);
  gtk_widget_set_size_request (button19, 112, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button19), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox17), label53, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Identifiant (N\302\260CIN): </b></span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed10), label37, 24, 88);
  gtk_widget_set_size_request (label37, 192, 40);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button3_c_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label40), entry10_c);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label43), entry11_c);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window4, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window4, entry7_c, "entry7_c");
  GLADE_HOOKUP_OBJECT (window4, entry8_c, "entry8_c");
  GLADE_HOOKUP_OBJECT (window4, entry9_c, "entry9_c");
  GLADE_HOOKUP_OBJECT (window4, entry10_c, "entry10_c");
  GLADE_HOOKUP_OBJECT (window4, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window4, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window4, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window4, entry11_c, "entry11_c");
  GLADE_HOOKUP_OBJECT (window4, entry12_c, "entry12_c");
  GLADE_HOOKUP_OBJECT (window4, label35, "label35");
  GLADE_HOOKUP_OBJECT (window4, label36, "label36");
  GLADE_HOOKUP_OBJECT (window4, label38, "label38");
  GLADE_HOOKUP_OBJECT (window4, label39, "label39");
  GLADE_HOOKUP_OBJECT (window4, label40, "label40");
  GLADE_HOOKUP_OBJECT (window4, label41, "label41");
  GLADE_HOOKUP_OBJECT (window4, label42, "label42");
  GLADE_HOOKUP_OBJECT (window4, label43, "label43");
  GLADE_HOOKUP_OBJECT (window4, label44, "label44");
  GLADE_HOOKUP_OBJECT (window4, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (window4, label45, "label45");
  GLADE_HOOKUP_OBJECT (window4, label46, "label46");
  GLADE_HOOKUP_OBJECT (window4, label47, "label47");
  GLADE_HOOKUP_OBJECT (window4, label48, "label48");
  GLADE_HOOKUP_OBJECT (window4, label49, "label49");
  GLADE_HOOKUP_OBJECT (window4, label50, "label50");
  GLADE_HOOKUP_OBJECT (window4, label51, "label51");
  GLADE_HOOKUP_OBJECT (window4, label52, "label52");
  GLADE_HOOKUP_OBJECT (window4, button19, "button19");
  GLADE_HOOKUP_OBJECT (window4, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window4, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window4, image17, "image17");
  GLADE_HOOKUP_OBJECT (window4, label53, "label53");
  GLADE_HOOKUP_OBJECT (window4, label37, "label37");

  return window4;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed11;
  GtkWidget *entry13_c;
  GtkWidget *entry14_c;
  GtkWidget *button20;
  GtkWidget *alignment19;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label56;
  GtkWidget *button21;
  GtkWidget *alignment20;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label58;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label57;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("authentification"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window2), fixed11);

  entry13_c = gtk_entry_new ();
  gtk_widget_show (entry13_c);
  gtk_fixed_put (GTK_FIXED (fixed11), entry13_c, 160, 72);
  gtk_widget_set_size_request (entry13_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13_c), 8226);

  entry14_c = gtk_entry_new ();
  gtk_widget_show (entry14_c);
  gtk_fixed_put (GTK_FIXED (fixed11), entry14_c, 160, 144);
  gtk_widget_set_size_request (entry14_c, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14_c), 8226);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed11), button20, 96, 208);
  gtk_widget_set_size_request (button20, 144, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button20), alignment19);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("login"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox18), label56, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed11), button21, 264, 208);
  gtk_widget_set_size_request (button21, 184, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button21), alignment20);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Cr\303\251er votre compte"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox19), label58, FALSE, FALSE, 0);

  label54 = gtk_label_new (_("Password"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed11), label54, 40, 144);
  gtk_widget_set_size_request (label54, 96, 25);

  label55 = gtk_label_new (_("Username"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed11), label55, 40, 72);
  gtk_widget_set_size_request (label55, 104, 25);

  label57 = gtk_label_new ("");
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed11), label57, 384, 112);
  gtk_widget_set_size_request (label57, 192, 32);

  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_button2_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button2_creation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window2, entry13_c, "entry13_c");
  GLADE_HOOKUP_OBJECT (window2, entry14_c, "entry14_c");
  GLADE_HOOKUP_OBJECT (window2, button20, "button20");
  GLADE_HOOKUP_OBJECT (window2, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window2, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window2, image18, "image18");
  GLADE_HOOKUP_OBJECT (window2, label56, "label56");
  GLADE_HOOKUP_OBJECT (window2, button21, "button21");
  GLADE_HOOKUP_OBJECT (window2, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window2, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window2, image19, "image19");
  GLADE_HOOKUP_OBJECT (window2, label58, "label58");
  GLADE_HOOKUP_OBJECT (window2, label54, "label54");
  GLADE_HOOKUP_OBJECT (window2, label55, "label55");
  GLADE_HOOKUP_OBJECT (window2, label57, "label57");

  return window2;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed12;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkWidget *button25;
  GtkWidget *button26;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("menu"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window5), fixed12);

  button22 = gtk_button_new_with_mnemonic (_("gestion capteurs"));
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed12), button22, 104, 40);
  gtk_widget_set_size_request (button22, 160, 40);

  button23 = gtk_button_new_with_mnemonic (_("gestion calendrier"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed12), button23, 104, 96);
  gtk_widget_set_size_request (button23, 160, 40);

  button24 = gtk_button_new_with_mnemonic (_("gestion ouvrier"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed12), button24, 104, 152);
  gtk_widget_set_size_request (button24, 160, 40);

  button25 = gtk_button_new_with_mnemonic (_("gestion d'equipement"));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed12), button25, 104, 208);
  gtk_widget_set_size_request (button25, 160, 40);

  button26 = gtk_button_new_with_mnemonic (_("gestion troupeaux"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed12), button26, 104, 264);
  gtk_widget_set_size_request (button26, 160, 40);

  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_g_capteurs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_g_calendrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_g_ouvrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25, "clicked",
                    G_CALLBACK (on_g_equipement_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window5, button22, "button22");
  GLADE_HOOKUP_OBJECT (window5, button23, "button23");
  GLADE_HOOKUP_OBJECT (window5, button24, "button24");
  GLADE_HOOKUP_OBJECT (window5, button25, "button25");
  GLADE_HOOKUP_OBJECT (window5, button26, "button26");

  return window5;
}

